"""add_role_to_employee

Revision ID: 042d98473d61
Revises: ec98b1dd5ed5
Create Date: 2026-06-01 14:14:11.891861

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "042d98473d61"
down_revision: Union[str, Sequence[str], None] = "ec98b1dd5ed5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# Added by
_ROLE_ENUM = sa.Enum("UI", "UX", "Developer", "HR", name="employeerole")


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    _ROLE_ENUM.create(op.get_bind(), checkfirst=True)

    op.add_column(
        "employees",
        sa.Column(
            "role",
            _ROLE_ENUM,
            server_default="Developer",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("employees", "role")
    # ### end Alembic commands ###
