"""add_extrafields_to_employee

Revision ID: 9af78f3e0b09
Revises: b7589228dea5
Create Date: 2026-06-10 16:16:22.968474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9af78f3e0b09'
down_revision: Union[str, Sequence[str], None] = 'b7589228dea5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


_STATUS_ENUM=sa.Enum('Probation', 'Active', 'Inactive', name='employeestatus')

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    _STATUS_ENUM.create(op.get_bind(), checkfirst=True)
    
    op.add_column('employees', sa.Column('status', _STATUS_ENUM, server_default='Probation', nullable=False))
    op.add_column('employees', sa.Column('experience', sa.Integer(), server_default='0', nullable=False))
    
    op.add_column('employees', sa.Column('alternate_id', sa.String(length=20), nullable=True))
    op.execute("UPDATE employees SET alternate_id = 'EMP' || id WHERE alternate_id IS NULL")
    op.alter_column('employees','alternate_id', nullable=False)

    op.add_column('employees', sa.Column('joining_date', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'joining_date')
    op.drop_column('employees', 'alternate_id')
    op.drop_column('employees', 'experience')
    op.drop_column('employees', 'status')
    # ### end Alembic commands ###
