"""alter_department_name_type

Revision ID: ec98b1dd5ed5
Revises: 6a249bfe1b1a
Create Date: 2026-05-30 21:05:05.495656

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ec98b1dd5ed5"
down_revision: Union[str, Sequence[str], None] = "6a249bfe1b1a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    op.execute("CREATE EXTENSION IF NOT EXISTS citext")
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "departments",
        "name",
        existing_type=sa.VARCHAR(length=20),
        type_=postgresql.CITEXT(length=20),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "departments",
        "name",
        existing_type=postgresql.CITEXT(length=20),
        type_=sa.VARCHAR(length=20),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
